services:
  # 1) Web API: OAuth + callback + работа с БД
  - type: web
    name: tracker-bot-auth1
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: BASE_URL
        sync: false
      - key: YANDEX_CLIENT_ID
        sync: false
      - key: YANDEX_CLIENT_SECRET
        sync: false
      - key: YANDEX_ORG_ID
        sync: false
      - key: DATABASE_URL
        sync: false

  # 2) Bot: тоже web (чтобы Render был доволен портом), внутри polling
  - type: web
    name: tracker-bot-bot1
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_web.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: BOT_TOKEN
        sync: false
      - key: BASE_URL
        sync: false
